package com.pensionsure.model;

/**
 * Records the outcome of matching a single field between a PDARecord and a Submission.
 *
 * One MismatchFlag is produced per field (name / dob / address) by MismatchEngine.
 * Together they form a MatchReport. This entity is also persisted to the database
 * so that historical match results can be reviewed without re-running the engine.
 *
 * WHY store the recommendation here rather than computing it on-the-fly in the UI?
 * The recommendation is generated by the MatchStrategy at match-time when it has full
 * context (which strategy, what threshold). Storing it means the UI layer is dumb —
 * it just displays data, not business logic. It also means the DB can be queried for
 * "all past recommendations for a pensioner" without calling the engine again.
 */
public class MismatchFlag {

    private int id;
    private int submissionId;

    // e.g., "name", "dob", "address" — matches the submitted field name for display.
    private String fieldName;

    // 0.0 (completely different) to 1.0 (identical) — produced by MatchStrategy.
    private double confidenceScore;

    // true if the score fell below the strategy's threshold (i.e., a mismatch was detected).
    private boolean flagged;

    // Human-readable explanation, e.g., "Name spelling differs slightly — verify PPO details".
    private String recommendation;

    public MismatchFlag() {}

    public MismatchFlag(int submissionId, String fieldName, double confidenceScore,
                        boolean flagged, String recommendation) {
        this.submissionId = submissionId;
        this.fieldName = fieldName;
        this.confidenceScore = confidenceScore;
        this.flagged = flagged;
        this.recommendation = recommendation;
    }

    // ---- Getters & Setters -----------------------------------------------

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getSubmissionId() { return submissionId; }
    public void setSubmissionId(int submissionId) { this.submissionId = submissionId; }

    public String getFieldName() { return fieldName; }
    public void setFieldName(String fieldName) { this.fieldName = fieldName; }

    public double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(double confidenceScore) { this.confidenceScore = confidenceScore; }

    public boolean isFlagged() { return flagged; }
    public void setFlagged(boolean flagged) { this.flagged = flagged; }

    public String getRecommendation() { return recommendation; }
    public void setRecommendation(String recommendation) { this.recommendation = recommendation; }

    @Override
    public String toString() {
        return "MismatchFlag{field='" + fieldName + "', score=" +
               String.format("%.3f", confidenceScore) + ", flagged=" + flagged + "}";
    }
}
